spring.application.name=BenidormHolidays
spring.datasource.url=jdbc:postgresql://localhost:5433/BenidormHolidays?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.data.rest.base-path=/api
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=debug
server.tomcat.max-part-count=30
#file.upload-dir=/var/www/fotos/uploads
file.upload-dir=C:/fotos/uploads
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=care24web@gmail.com
spring.mail.password=bnmxjaahxvcxbfrl
#spring.mail.password=webcare24
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true